[options]
admin_passwd = admin_super_secret_password

; Filtro y fijación de BD
db_name = spark_erp_db_dev
dbfilter = ^spark_erp_db_dev$
list_db = False
db_maxconn = 32

; Addons y módulos
without_demo = True
server_wide_modules = base,web
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/custom

; Logs y Red
http_interface = 0.0.0.0
log_level = info